# Parallelisation options
USE_MPI = TRUE
USE_OMP = FALSE

# Debug mode?
DEBUG = FALSE

# Profiling
PROFILE       = FALSE
TRACE_PROFILE = FALSE
COMM_PROFILE  = FALSE
TINY_PROFILE  = FALSE

# Here are settings not specific to each problem, 
# and which we probably don't want to change 
include ../Make.incflo
