AMREX_HOME ?= ../../amrex
TOP = ..

EBASE = incflo

BL_NO_FORT = FALSE

DIM = 3

PRECISION  = DOUBLE

TINY_PROFILE = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = FALSE

USE_HYPRE = FALSE

USE_EB = TRUE

include ../src/Make.incflo
