version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "weekly"
    directory: /
    allow:
      - dependency-name: "submods/amrex"
      - dependency-name: "submods/AMReX-Hydro"
