COMP          = gnu
USE_MPI       = FALSE
USE_OMP       = FALSE
USE_CUDA      = FALSE
DEBUG         = FALSE
USE_HYPRE     = FALSE
PROFILE       = FALSE
TINY_PROFILE  = FALSE

INCFLO_HOME := ../
include $(INCFLO_HOME)/make.incflo
