COMP          = intel
USE_MPI       = TRUE
USE_OMP       = FALSE
DEBUG         = FALSE
USE_HYPRE     = FALSE
PROFILE       = FALSE
TINY_PROFILE  = FALSE

INCFLO_HOME := ../
include $(INCFLO_HOME)/make.incflo
