#ifndef FVM_H
#define FVM_H

#include "amr-wind/fvm/curvature.H"
#include "amr-wind/fvm/divergence.H"
#include "amr-wind/fvm/gradient.H"
#include "amr-wind/fvm/laplacian.H"
#include "amr-wind/fvm/strainrate.H"
#include "amr-wind/fvm/vorticity.H"
#include "amr-wind/fvm/vorticity_mag.H"
#include "amr-wind/fvm/qcriterion.H"
#include "amr-wind/fvm/filter.H"

/**
 *  \defgroup fvm Finite-Volume Operators
 *
 *  Finite-Volume Operators
 *
 *  The `fvm` namespace defines finite-volume stencils and associated operators
 *  (e.g., gradient, divergence, laplacian, etc.) that are commonly used when
 *  solving partial differential equations using finite volume methods.
 */

#endif /* FVM_H */
