#!/bin/bash -l

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

AMREX_BASE=$1
if [ -z "${AMREX_BASE}" ]; then
    echo "File name base is not set. Abortingt."
    exit 1
fi

SORT=$2
if [ -z "${SORT}" ]; then
    SORT=5
fi

list=$(eval ls -v ${AMREX_BASE}*[0123456789])
for FILE in $(echo ${list}); do

    RC=$(awk 'FNR == 2 {print}' $FILE)
    IC=$(awk 'FNR == 3 {print}' $FILE)
    STEP=${FILE##${AMREX_BASE}}

    if [ $RC -eq 14 ] && [ $IC -eq 2 ]; then
       echo "   "
       echo "   "
       echo "Step: ${STEP}"
       ${DIR}/ascii-tools --file ${FILE} --max-vel --sort ${SORT}
    fi
done
