#ifndef KYNEMA_WRAPPER_H
#define KYNEMA_WRAPPER_H

namespace exw_kynema {

#ifdef AMR_WIND_USE_KYNEMA
/*#include <string>
#include <ranges>
#include <type_traits>
#include <array>
#include <numbers>

#include <yaml-cpp/yaml.h>

#include "elements/beams/hollow_circle_properties.hpp"
#include "interfaces/components/aerodynamics.hpp"
#include "interfaces/components/inflow.hpp"
#include "interfaces/turbine/turbine_interface.hpp"
#include "interfaces/turbine/turbine_interface_builder.hpp"*/
#else
#endif

} // namespace exw_fast

#endif /* KYNEMA_WRAPPER_H */
