# Set amrex hydro options

set(HYDRO_SPACEDIM 3)
set(HYDRO_EB OFF)
set(HYDRO_MPI ${AMR_WIND_ENABLE_MPI})
set(HYDRO_OMP ${AMR_WIND_ENABLE_OPENMP})
set(HYDRO_FFT ${AMR_WIND_ENABLE_FFT})
if (AMR_WIND_ENABLE_CUDA)
  set(HYDRO_GPU_BACKEND CUDA CACHE STRING "HYDRO GPU type" FORCE)
elseif(AMR_WIND_ENABLE_ROCM)
  set(HYDRO_GPU_BACKEND HIP CACHE STRING "HYDRO GPU type" FORCE)
elseif(AMR_WIND_ENABLE_SYCL)
  set(HYDRO_GPU_BACKEND SYCL CACHE STRING "HYDRO GPU type" FORCE)
else()
  set(HYDRO_GPU_BACKEND NONE CACHE STRING "HYDRO GPU type" FORCE)
endif()

