      NAMELIST / BOUNDARY_CONDITIONS/&

      BC_TYPE, BC_X_w, BC_X_e, BC_Y_s, BC_Y_n, BC_Z_b, BC_Z_t,         &
      BC_Normal, BC_Center,                                            &
      BC_Hw_g, BC_Uw_g, BC_Vw_g, BC_Ww_g,                              &
      BC_Hw_T_g, BC_Hw_T_s, BC_Tw_g, BC_Tw_s, BC_C_T_g, BC_C_T_s,      &
      BC_Hw_X_g, BC_Xw_g, BC_C_X_g,                                    &
      BC_P_g, BC_T_g, BC_T_s,                        &
      BC_X_g, BC_X_s,  BC_U_g, BC_U_s, BC_V_g, BC_V_s, BC_W_g, BC_W_s, &
      BC_VOLFLOW_g, BC_VOLFLOW_s, BC_MASSFLOW_g, BC_MASSFLOW_s,        &
      BC_SHAKER_A, BC_SHAKER_F
