      NAMELIST / BOUNDARY_CONDITIONS/&

      BC_TYPE, &
      BC_X_w, BC_X_e,               &
      BC_Y_s, BC_Y_n,               &
      BC_Z_b, BC_Z_t,               &
      BC_Normal, BC_Center,         &
      BC_Hw, BC_Uw, BC_Vw, BC_Ww,   &
      BC_Hw_T, BC_Tw, BC_C_T,       &
      BC_P, BC_T,                   &
      BC_U, BC_V, BC_W,       &
      BC_VOLFLOW, BC_MASSFLOW,      &
      BC_SHAKER_A, BC_SHAKER_F
