name: AMR-Wind API docs

on:
  push:
    branches:
      - development
    paths:
      - 'amr-wind/**'
      - 'docs/doxygen/**'
      - '.github/workflows/api-docs.yml'

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install doxygen dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            doxygen graphviz
      - name: Build docs
        run: |
          doxygen ./docs/doxygen/Doxyfile
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/html
