name: AMR-Wind DPC++ CI

on:
  push:
    branches:
      - development
    paths:
      - 'cmake/**'
      - 'amr-wind/**'
      - 'submods/**'
      - 'unit_tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/dpcpp-ci.yml'
  pull_request:
    branches:
      - development
    paths:
      - 'cmake/**'
      - 'amr-wind/**'
      - 'submods/**'
      - 'unit_tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/dpcpp-ci.yml'

jobs:
  dpcpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare DPC++ environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libopenmpi-dev intel-oneapi-dpcpp-compiler intel-oneapi-mkl
      - name: Configure and build
        run: |
          set +e
          source /opt/intel/inteloneapi/setvars.sh
          set -e
          cmake -Bbuild \
            -DCMAKE_CXX_COMPILER=$(which dpcpp) \
            -DCMAKE_C_COMPILER=$(which clang) \
            -DAMR_WIND_ENABLE_MPI=OFF \
            -DAMR_WIND_ENABLE_DPCPP=ON .
          cmake --build build -- -j $(nproc)
