name: AMR-Wind Intel OneAPI CI

on:
  push:
    branches:
      - development
    paths:
      - 'cmake/**'
      - 'amr-wind/**'
      - 'submods/**'
      - 'unit_tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/dpcpp-ci.yml'
  pull_request:
    branches:
      - development
    paths:
      - 'cmake/**'
      - 'amr-wind/**'
      - 'submods/**'
      - 'unit_tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/dpcpp-ci.yml'

jobs:
  dpcpp:
    runs-on: ubuntu-latest
    name: Intel OneAPI ${{matrix.intel_type}}
    strategy:
      matrix:
        intel_type: [ICC, DPCPP]
        include:
          - intel_type: ICC
            oneapi_packages: intel-oneapi-dpcpp-cpp-compiler-pro
            cexe: icc
            cppexe: icpc
            enable_dpcpp: OFF
          - intel_type: DPCPP
            oneapi_packages: intel-oneapi-dpcpp-cpp-compiler intel-oneapi-mkl-devel
            cexe: clang
            cppexe: dpcpp
            enable_dpcpp: ON
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare DPC++ environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libopenmpi-dev ${{matrix.oneapi_packages}}
      - name: Configure and build
        run: |
          set +e
          source /opt/intel/oneapi/setvars.sh
          set -e
          cmake -Bbuild-${{matrix.intel_type}} \
            -DCMAKE_CXX_COMPILER=$(which ${{matrix.cppexe}}) \
            -DCMAKE_C_COMPILER=$(which ${{matrix.cexe}}) \
            -DAMR_WIND_ENABLE_MPI=OFF \
            -DAMR_WIND_ENABLE_DPCPP=${{matrix.enable_dpcpp}} .
          cmake --build build-${{matrix.intel_type}} -- -j $(nproc)
      - name: Unit tests
        if: ${{ matrix.intel_type == 'ICC' }}
        working-directory: ${{runner.workspace}}/build-${{matrix.intel_type}}
        run: ctest -j $(nproc) -L unit --output-on-failure
